### ISSUE TITLE
Unable to generate sift models

### ISSUE THREAD

**Issue by oars** [karlpauwels/simtrack#10]
Trying to run your tutorial and I'm running into this problem. Any suggestions?

```
rosrun interface cmd_line_generate_sift_model `pwd`/src/simtrack/data/object_models/ros_hydro/ros_hydro.obj
terminate called after throwing an instance of 'std::runtime_error'
  what():  Device1D::Device1D: unknown error
[1]    31009 abort (core dumped)  rosrun interface cmd_line_generate_sift_model 
```

**Comment by karlpauwels** [comment]
My guess is there's some issue with your CUDA installation. You may want to have a look here and try running the samples from the CUDA SDK:
http://stackoverflow.com/questions/29761036/cudamalloc-caused-unknown-errors-in-cuda

**Comment by oars** [comment]
Thanks for the quick pointer. Fixed the issue by reinstalling the toolkit.

**Comment by ZhengYi0310** [comment]
Hi I've running into the same issue as you, and I tried reinstall cuda 6.5 toolkit, but it still throws this error, as the following:

terminate called after throwing an instance of 'std::runtime_error'
  what():  Device1D::Device1D: unknown error
Aborted (core dumped)

Can you tell me how do you solve this in a more detail ?
Thx

**Comment by karlpauwels** [comment]
You may want to try installing the latest CUDA version and make sure that the samples from the sdk work correctly. In particular try: deviceQuery, bandwidthTest and fluidsGL

**Comment by ZhengYi0310** [comment]
Hi Dr.Pauwels,
     Thanks for the reply. Unfortunately the workstation in my lab is kind of old, it has a graphics card Nvidia Quadro NVS 290, which can only support cuda-6.5 with driver 340.96.
     After I reboot the system, re-running the command give me the following error:
     `ResizePyramid: out of memory`
      `FilterV: invalid device function`
      `FilterH: invalid device function` 
      `FilterV: invalid device function` 
      `FilterH: invalid device function`
      `FilterV: invalid device function`
      `FilterH: invalid device function`
      `FilterV: invalid device function`
      `FilterH: invalid device function` 
      `.......the same stuff......`
      `PyramidCU::GenerateFeatureList:  invalid device function` 
      `terminate called after throwing an instance of 'std::runtime_error`
      `what():  SiftGPU failed`
      `Aborted (core dumped)`
      Here is the result after running nvidia-smi:
      ![smi](https://cloud.githubusercontent.com/assets/8685125/14903252/c2a92d18-0d54-11e6-91d6-b2221be993da.png)
      Here is the result after deviceQuery:
      ![devicequery](https://cloud.githubusercontent.com/assets/8685125/14903268/d1cac752-0d54-11e6-88b7-a11647782b69.png)
      Here is the result after bandwidthTest:
      ![bandwidthtest](https://cloud.githubusercontent.com/assets/8685125/14903278/e59b7c7c-0d54-11e6-8da3-3d784c6dd666.png)
      Here is the result after fluidsGL:
      ![fluidsgl](https://cloud.githubusercontent.com/assets/8685125/14903293/faa54a08-0d54-11e6-8616-48ef5c4ad6b2.png)

   P.S:The compilation of simtrack will fail unless I comment all lines including "compute_52" in the cmake file, because my gpu doesn't support this architecture.
Thx

**Comment by ZhengYi0310** [comment]
It looks like I need to use compute_11 and sm11 ?

**Comment by karlpauwels** [comment]
I'm afraid you're not going to be able to run it on that GPU. There simply isn't enough memory available.

Xtion-style sensors (640x480) require at least 1.3 GB of free GPU memory (300 MB tracking, 1 GB detection) for the three example objects. Use nvidia-smi to check memory usage.
Kinect v2 sensors (1920x1080) require at least 2.6 GB of free GPU memory (400 MB tracking at QHD, 2.2 GB detection at full HD). The resolution can be lowered for detection but this is not ideal.

**Comment by ZhengYi0310** [comment]
I see, thanks very much for the reply.
