### ISSUE TITLE
Kinect V2 - incorrect depth or image size error when switching cameras

### ISSUE THREAD

**Issue by MannyKayy** [karlpauwels/simtrack#13]
Simtrack crashes whenever there is an attempt to switch between cameras with different resolutions.. Specifically between the camera's of the PR2 and those of the Kinect V2..

Depth error
`
terminate called after throwing an instance of 'std::runtime_error'
  what():  MultiRigidTracker::convertDepth:: incorrect depth size
`

Image error
`
terminate called after throwing an instance of 'std::runtime_error'
  what():  MultiRigidTracker::convertImage:: incorrect image size
`

**Comment by karlpauwels** [comment]
This is expected behavior. To increase performance, all GPU storage is allocated at creation time. This depends on the image size. You can try creating separate trackers (and maybe also detectors) for the PR2 and for the Kinect V2. This should work but will require more memory.
