### ISSUE TITLE
Simtrack on 16.04 & Kinetic

### ISSUE THREAD

**Issue by JimmyDaSilva** [karlpauwels/simtrack#16]
Hello @karlpauwels 
Thank you for the awesome work. It's really fast and convenient to use.
I would like to get this package on Ubuntu 16.04 and ROS Kinetic but I get issues.

First one is that you require OpenCV 2.4.8. I have commented out the version requirement because Kinetic uses OpenCV 3. 

Second more complex comes from Ogre

```
/home/jimmy/simtrack_ws/src/simtrack/rendering/src/ogre_multi_render_target.cpp: In constructor ‘render::OgreMultiRenderTarget::OgreMultiRenderTarget(std::__cxx11::string, int, int, Ogre::SceneManager*)’:
/home/jimmy/simtrack_ws/src/simtrack/rendering/src/ogre_multi_render_target.cpp:61:60: error: no matching function for call to ‘Ogre::SharedPtr<Ogre::GLTexture>::SharedPtr(Ogre::TexturePtr&)’
     GLuint id = static_cast<Ogre::GLTexturePtr>(rtt_texture)->getGLID();
```

Thank you for your help !

**Comment by karlpauwels** [comment]
Thanks Jimmy!
I've added a 'kinetic' branch with minimal changes required to compile and run a basic test on kinetic. Can you give it a try and let me know if you run into issues?

Many thanks,
Karl

**Comment by JimmyDaSilva** [comment]
Thanks @karlpauwels . I was stuck with the cuda modifications: `rtt_texture.staticCast<Ogre::GLTexture>()`

I made a few adjustments on my fork to make it compile:
https://github.com/JimmyDaSilva/simtrack/commit/18994a8f80c9068ceb86155fadb0c226d98623ed

The learning works but when I run the `main.launch` I get the following:

```
[ INFO] [1476793268.290370119]: Starting depth stream.
OpenCV Error: Assertion failed (confidence > 0 && confidence < 1) in run, file /tmp/binarydeb/ros-kinetic-opencv3-3.1.0/modules/calib3d/src/ptsetreg.cpp, line 178
terminate called after throwing an instance of 'cv::Exception'
  what():  /tmp/binarydeb/ros-kinetic-opencv3-3.1.0/modules/calib3d/src/ptsetreg.cpp:178: error: (-215) confidence > 0 && confidence < 1 in function run

[ INFO] [1476793269.333256138]: Stopping depth stream.
```

Do you have any idea which opencv function is complaining ?

Thanks again !

**Comment by JimmyDaSilva** [comment]
@karlpauwels I found a similar issue there:
https://github.com/code-iai/iai_kinect2/issues/237

So I change the param to 0.99 of confidence. The nodes compile and run, but unfortunately no objects are found...

I can't tell if the problem comes from here or from the changes of cuda/opencv

**Comment by karlpauwels** [comment]
Thanks for looking into this @JimmyDaSilva 
I managed to fix it now in the kinetic branch. Let me know if anything else pops up!

**Comment by JimmyDaSilva** [comment]
@karlpauwels Works !
But I insist that I needed #17 to make it compile properly
Thank you for your help :)
