### ISSUE TITLE
 Change the resolution

### ISSUE THREAD

**Issue by joowonkim** [karlpauwels/simtrack#18]
I am using Kinect v2. I want to know how to change the resolution to 1920x1080 when running on ros.

**Comment by JimmyDaSilva** [comment]
Easy! You just need to modify this launch file:
https://github.com/karlpauwels/simtrack/blob/master/simtrack_nodes/launch/multi-rigid_kinect2.launch

**Comment by TrinhTUHH** [comment]
Hi Jimmy,
when I replaced hd by qhd in these 3 lines, the program stopped when I hold the photo in front of the camera. When I replaced hd by sd, it works but nothing appeared in rqt windows. Do you know why?
 ```
 <remap from="rgb" to="/kinect2/hd/image_mono_rect" />
  <remap from="rgb/compressed" to="/kinect2/hd/image_mono_rect/compressed" />
 <remap from="rgb_info" to="/kinect2/hd/camera_info" />
```
