### ISSUE TITLE
Explicit statement in Readme of CUDA version

### ISSUE THREAD

**Issue by balloch** [karlpauwels/simtrack#2]
It should say in the README.md that the minimum CUDA Toolkit is 6.5, not just any toolkit. You shouldn't have to wait until install to see that the minimum CUDA Toolkit version is 6.5. At first glance, it may seem obvious, as the link links to the current stable version (toolkit 7.5, CUDA 7), but this is not compatible with 12.04, and many people already have CUDA 6 or 5.5 installed, especially those who are developing on a GTX-7xx or lower.

**Comment by karlpauwels** [comment]
Thanks for pointing this out! I've updated the README.
