### ISSUE TITLE
Unable to rosrun. Getting error "Executable not found"

### ISSUE THREAD

**Issue by trshashank** [karlpauwels/simtrack#23]
System Specs:
- Ubuntu 16.04 
- ROS Kinetic
- Open CV 2.4.8
- CUDA 8.0
- iah_kinect2 drivers.
I am following the steps provided in the readme to recreate the simtrack package. However, after performing a "catkin_make --pkg simtrack", on executing the following  rosrun command 
**rosrun interface cmd_line_generate_sift_model `pwd`/src/simtrack/data/object_models/ros_fuerte/ros_fuerte.obj**
I receive an error saying the executable "rosrun interface cmd_line_generate_sift_model" was not found. 
On a simple google search, I came across the following article:
http://answers.ros.org/question/154561/why-cant-roslaunch-or-rosrun-find-my-executable/
 However, I have already done everything that the article has suggested.
Please suggest any other changes that I need to make in order to succesfully recreate the package.

**Comment by karlpauwels** [comment]
If you use the master branch, a full compilation will fail. For Kinetic you should give the Kinetic-branch a try: https://github.com/karlpauwels/simtrack/tree/kinetic
You should also compile with `catkin_make -DCMAKE_BUILD_TYPE="Release"` since the `--pkg`-switch compiles only the specified package and simtrack depends on other packages in this repo.

**Comment by trshashank** [comment]
Thank you Karl for your reply. I tried to pull the changes from the Kinetic branch and I was successfully able to execute rosrun. 
Also, in the kinect branch you have provided you have updated the OPENCV from 2.4 to 3.1. When making use of the Kinect camera, I was not able to connect to the device. Is this because of the OPENCV version? Do you recommend any reverts/ changes to successfully connect to Kinect.

**Comment by trshashank** [comment]
I  was able to find a workaround for the above issue by installing openni2 drivers on my system
