### ISSUE TITLE
New objects not detected:

### ISSUE THREAD

**Issue by trshashank** [karlpauwels/simtrack#25]
Hello, 

This package works very well for the models given pre loaded in the package i.e. ros_hydro, ros_fuerte. However, when I include 3d objects which I have modeled using AutoDesk Remake, I am unable to detect this object using simtrack.

I am working with Ubuntu 16.04 and ROS Kinetic. 
Also, I have added my objects to the same path as the pre loaded models and included the object name in the multi_rigid_launch file.

Could anyone who has incorporated new objects to simtrack please help me here.

**Comment by JimmyDaSilva** [comment]
I have been using simtrack on both Ubuntu 14.04 and 16.04 on kinetic and indigo and it works great !
My guess is that you forgot some of the object modeling steps to do on blender:
http://www.karlpauwels.com/simtrack/object-modeling/

**Comment by trshashank** [comment]
Thanks for the reply Jimmy. I realized that I had not scaled the object to the real world coordinates. I was able to visualize the object in Blender and realized that scaling was necessary. Now I am able to work with real time objects. Thanks for the help.
