### ISSUE TITLE
Cannot Detect Preload Model (i.e. ros_hydro, ros_fuerte)

### ISSUE THREAD

**Issue by pvmilk** [karlpauwels/simtrack#26]
The simtrack runs fine and /simtrack/image can be seen, but no green tracking or anything. 
Also /simtrack/DepthCloud display nothing. 

I followed the README.md on the first page strictly, except

1.) My system
- Ubuntu 14.04
- ROS Indiago
- GeForce GTX 1080 (one GPU system)
- Kinect2 (libfreekinect2)

2.) roslaunch kinect2_bridge is run with depth_device:=0 parameters instead of depth_device:=1

3.) models_to_print.pdf is measured 9.5cm instead of 10cm

4.) The attach patch is applied to make it compiled with my system. 
[simtrack1080.patch.zip](https://github.com/karlpauwels/simtrack/files/942487/simtrack1080.patch.zip)

Thank you in advanced.

**Comment by JimmyDaSilva** [comment]
Is the kinect2 calibrated ?
Try to print again the models without any margin to make sure the model has the right size.

Why did you change the CMakelist.txt s ?

**Comment by pvmilk** [comment]
Thanks for your quick response. 

The kinect2 is calibrated. 
I will try to reprint the model again  (maybe 2moro)

CMakelists.txt are changed for 
- path of cub library 
- GeForce 1080 is seemed to be compute 60 (it compiles without this change, but cannot find the device and finally got seg fault) 

Is /simtrack/DepthCloud suppose to show anything?

**Comment by pvmilk** [comment]
Tried with the printed_model with perfect 10cm, 
but still got nothing in /simtrack/image
(only a monochrome image of the scene without any overlay-ed color). 

Trying to debug on my own: 
- No log can be found in ~/.ros/log/xxxxxxxxxxxxxxxxxx....xxxxxx/simtrack-1.log
- Sometimes, the process is abort with the following error
ComputeOrientation:          an illegal memory access was encountered
terminate called after throwing an instance of 'std::runtime_error'
  what():    Device1D::copyTo:  an illegal memory access was enbountered. 

Do you think this has something to do with the [cub library](https://nvlabs.github.io/cub/) I used (cub-1.6.4)? or the compile flag (-gencode=arch=compute_60,code=sm_60) which I specified for GeForce GTX 1080?

**Comment by pvmilk** [comment]
Found the bugs. Sorry for the troubling. 

the compute_arch for GeForce GTX 1080 is -gencode=arch=compute_61,code=sm_61. 

All works fine, thank you!
