### ISSUE TITLE
Simtrack for commercial purpose, but SIFT is patented!

### ISSUE THREAD

**Issue by TrinhNC** [karlpauwels/simtrack#32]
I just notice that Simtrack uses SIFT key points which is a non-free module in OpenCV. However the Simtrack's License says that it is available for commercial purposes. So I'm a bit confused here, and my question is can I use it in commercial project?

**Comment by karlpauwels** [comment]
Thanks for bringing this up.

The SimTrack code is indeed released under the BSD license. It does use SiftGPU though and that has a different [license](https://github.com/karlpauwels/simtrack/blob/master/siftgpu/license.txt). The SiftGPU code is included here for convenience (together with a new `CMakeLists.txt` file). It seems the project website is no longer active so I have no idea about the current state of SiftGPU.

There is an alternative MIT-licensed project that you could look into: https://github.com/Celebrandil/CudaSift
Depending on the country, you may have to replace SIFT altogether though for commercial purposes.

I've added a sentence to the main `README.md` to highlight this.

**Comment by TrinhNC** [comment]
Thanks for your reply!
> Depending on the country, you may have to replace SIFT altogether though for commercial purposes.

Am in Germany now so am I allowed to use it? 
And by this 

> There is an alternative MIT-licensed project that you could look into: https://github.com/Celebrandil/CudaSift

you mean I can replace the SiftGPU part in SimTrack package by this CudaSift?

**Comment by karlpauwels** [comment]
I'm afraid I can't give you legal advice :smile:

Yes it is possible to replace SiftGPU but this is not a plug-and-play kind of thing. It will require quite a bit of coding, testing, etc.

**Comment by TrinhNC** [comment]
Ok, thank you for the information!
