### ISSUE TITLE
Modeled objects specifics 

### ISSUE THREAD

**Issue by ayertay** [karlpauwels/simtrack#35]
Hello,

Again, I'm new to ROS, and thank you for your help. I made a model of plant leaf from paper(sort of). It's green. Then used ReCap Photo to get the .obj file. I followed the tutorial, generated the SIFT model. However, camera doesn't identify it. I launched rqt and showed the ros_hydro model to the camera, and it identified it. However, it didn't identify my leaf. Question: Should my leaf have some writings on it as every other example models? 

![paper_leaf](https://user-images.githubusercontent.com/8834731/33738581-9d638b56-db67-11e7-844d-446d37539416.jpeg)

![leaf_obj](https://user-images.githubusercontent.com/8834731/33738584-a24c6ab6-db67-11e7-82c9-20fb800c656b.jpeg)

**Comment by JimmyDaSilva** [comment]
@ayertay Simtrack is based on SIFT features. So you need to use objects with meaningful textures.
Basically not one-colored objects.

**Comment by ayertay** [comment]
@JimmyDaSilva thank you for reply! Indeed, I changed to other model with texture and it started to detect. Do you have tips on how can I improve the tracking? It identifies my model only from close distance (less than 1 meter) and loses track easily, whereas when I show the demo model ( ros hydro paper) it can detect from 3 meters away and holds well at angles. 

![ros_leaf](https://user-images.githubusercontent.com/8834731/33773728-d7c32294-dc06-11e7-9f14-d1b5ce111a4e.jpeg)

This is the model I have.

**Comment by JimmyDaSilva** [comment]
The texture needs to be well formed with respect to the real object. From the meshlab view of your object it seems that the texture is quite blury.
Apart from that I don't see anything wrong here. Maybe the size of your mesh is too different from the real object ?

**Comment by ayertay** [comment]
Thank you for your help! I'm using a more textured object. It works for me for now.
