### ISSUE TITLE
Absolute pose estimation doubt

### ISSUE THREAD

**Issue by davizinho5** [karlpauwels/simtrack#38]
Hello, 

If I understand correctly, the pose estimation depends con Sift features of the texture. Are these features related somehow to an absolute frame on the object, e.g., the centre of mass of the 3D model of the object? In case it is, how is it computed?
I'm not sure but it seems to me that if I move the object, and different features are visible to the camera, then the estimation pose given by the TF tree changes with respect to the model, but it could also be some noise due to the movement. 

Thanks for the help!

**Comment by JimmyDaSilva** [comment]
@davizinho5 From what I understood it's the center defined when modeling the objects.
It can be changed on blender via the procedure described in the tutorial : http://www.karlpauwels.com/simtrack/object-modeling/

**Comment by davizinho5** [comment]
Hi, thanks Jimmy, it looks like I made a mistake during modelling and the the estimation frame was located in a very strange position, but it looks good now.

**Comment by JimmyDaSilva** [comment]
@davizinho5 Glad I can help.
Do not forget to close the issue if you're good.
