### ISSUE TITLE
Does SimTrack work with textureless (non-textured) objects?

### ISSUE THREAD

**Issue by TrinhNC** [karlpauwels/simtrack#40]
Has anyone tried to use SimTrack for detecting non-textured objects?

**Comment by JimmyDaSilva** [comment]
@TrinhTUHH SimTrack uses SIFT keypoints, so no.

**Comment by TrinhNC** [comment]
@JimmyDaSilva Hi Silva, do you know any similar package that can deal with textureless objects?

**Comment by JimmyDaSilva** [comment]
Nop. No proper package.
I know the linemod method is well famous. It's been implemented in opencv and PCL. The default method uses contours and color gradient, but can also be tweaked a little bit.
Problem is I couldn't get good results from ORK which implemented it so at some point I tried directly the opencv version and it was fine
