### ISSUE TITLE
unable to launch simtrack _nodes main_kinect2.launch

### ISSUE THREAD

**Issue by chandanlal92** [karlpauwels/simtrack#42]
I am getting this error while running main_kinect2.launch.
 WARN] [1542027466.949893288]: Messages of type 0 arrived out of order (will print only once)
terminate called after throwing an instance of 'std::runtime_error'
  what():  Duration is out of dual 32-bit range
[Info] [DepthPacketStreamParser] 7 packets were lost
[Info] [Freenect2DeviceImpl] stopping...
[Info] [Freenect2DeviceImpl] canceling rgb transfers...
[simtrack-7] process has died [pid 5940, exit code -6, cmd /home/chandan_main/catkin_ws/devel/lib/simtrack_nodes/multi_rigid_node rgb:=/kinect2/hd/image_mono_rect rgb/compressed:=/kinect2/hd/image_mono_rect/compressed rgb_info:=/kinect2/hd/camera_info depth:=/kinect2/qhd/image_depth_rect depth/compressed:=/kinect2/qhd/image_depth_rect/compressed __name:=simtrack __log:=/home/chandan_main/.ros/log/8bea56e2-e67a-11e8-863b-107b4447c528/simtrack-7.log].
log file: /home/chandan_main/.ros/log/8bea56e2-e67a-11e8-863b-107b4447c528/simtrack-7*.log

kinect2_bridge is working fine with cuda and opencl. I am able to get rosrun interface object model
cmd_line_generate_sift_model `pwd`/src/simtrack/data/object_models/ros_fuerte/ros_fuerte.obj
I am just getting this error and not able to get my detection

**Comment by chandanlal92** [comment]
Previously,It was working  properly and able to detect my object but once I had reinstall my ROS after that I am getting this issues. Please help me out.

**Comment by karlpauwels** [comment]
Not sure if I can replicate this.

Please do a debug-compile:
``
catkin_make -DCMAKE_BUILD_TYPE="Debug"
``
and run with GDB attached:
http://wiki.ros.org/roslaunch/Tutorials/Roslaunch%20Nodes%20in%20Valgrind%20or%20GDB
so that we can verify that the error is in simtrack and hopefully locate it in the source code.

**Comment by chandanlal92** [comment]
Thank you!!! It worked...🙂🙂
