### ISSUE TITLE
Stopped working with Kinect

### ISSUE THREAD

**Issue by balloch** [karlpauwels/simtrack#7]
Hey there, 

Suddenly my previously working system, using Kinect (not Kinect2) has stopped working. Was wondering if you could help look into this. `<roslaunch simtrack_nodes main_kinect.launch>` still appears to be running without an issue, and topics are being opened, but nothing is being published, even with the test objects. Where can I look for debug info?

Cheers,

Jon

**Comment by balloch** [comment]
to make this more interesting, I tried to rerun catkin make, it bombs on 

`d_multiple_rigid_pose_sparse.cpp`

[simtrack-catkin_make-errors.txt](https://github.com/karlpauwels/simtrack/files/87673/simtrack-catkin_make-errors.txt)

UPDATE: I have tried deleting the source, re-downloading with `wstool update` and rebuilding. still errors in the same place.

**Comment by karlpauwels** [comment]
Hi Jon,

I would first check if the kinect (and/or its driver) is still working. You can try running freenect, e.g. through camera_kinect.launch and see if the kinect topics are still published. They're easy to see using for example rqt.

For your compilation problem, try a fresh clone of the repository and recompile it. Maybe something has changed in your code?

Hope this helps.

**Comment by balloch** [comment]
Hey Karl,

I have tried a fresh clone to no avail. I am a little lost as to what this could be. 

one thought: the `vector` calls in the file I listed in the text file output, what is the namespace/class they are suppose to belong to? I tried changing the offending terms to `std::vector` (and later, when getting similar errors on a few `string` calls without an explicit namespace I changed them to `std::string`), which allowed it to build successfully, but then the topics wouldn't quite initiate properly when I run `roslaunch simtrack_nodes main.launch`. That is to say, I could still get an output from the camera topics, but all of the simtrack topics showed nothing. More indicative of a problem, I tried to prepare a new model, for tracking using the   `rosrun interface cmd_line_generate_sift_model` code, and this simply bombed with a "Segmentation fault (core dumped)" exit. no additional information. 

Looking forward to your input. I will continue to update letting you know what is going on

**Comment by karlpauwels** [comment]
Thanks Jon,

There is definitely some namespace pollution going on. I have been able to replicate your problem but the error seems to be due to Ogre. It's a bit tricky to fix so I'm going to need some more time. Will get back to you on this asap.

Karl

**Comment by balloch** [comment]
Thanks Karl. Functionality for me is of the upmost importance, so do you have any recommendations as to what version still works, and with what version of ROS and Ubuntu?
-Jon

**Comment by balloch** [comment]
Also, is there a way to debug this in Eclipse? Or did you build the whole project in a text editor?

**Comment by karlpauwels** [comment]
Sorry about the delay. The current version works with Ubuntu 14.04 and ROS Indigo. Both are LTS versions and thus recommended in general. As IDE I use QtCreator which is very convenient for debugging. You may want to stick to [version 3.2.2](https://download.qt.io/official_releases/qtcreator/3.2/3.2.2/) though since higher versions have issues with finding all headers for text completion. Also have a look here for hints: http://wiki.ros.org/IDEs#QtCreator

**Comment by karlpauwels** [comment]
I cleaned up the namespace references in the last commit: 2f7cc0777dd517cf62294dc7fe00c39ed5412c1b
Are you still experiencing problems now?

**Comment by balloch** [comment]
Hey karl,
thanks, namespace issues gone, but the main problem persists - getting a core dump on the `rosrun interface cmd_line_get_sift_model` for the samples. I'll start a new issue so you can close this one, thanks
