### ISSUE TITLE
Segmentation fault (core dumped) on get_sift_model

### ISSUE THREAD

**Issue by balloch** [karlpauwels/simtrack#9]
The main library builds for me, and I source the setup.bash file in the devel folder, but when I run

`rosrun interface cmd_line_get_sift_model`pwd`/src/simtrack/data/object_models/ros_groovy/ros_groovy.obj` 

To test the samples, it doesn't work. For a second nothing happens, and then I get 

Segmentation fault (core dumped)

Can you suggest anything I could run to verify that my system is properly setup?

**Comment by karlpauwels** [comment]
I have attached my catkin_make output. Can you compare this to yours? This should give us a rough idea of differences in system setup.
Thanks.
[catkin_make_output.txt](https://github.com/karlpauwels/simtrack/files/120595/catkin_make_output.txt)

**Comment by balloch** [comment]
Thanks. 

So, unfortunately, in the time that I wasn't checking github, I couldn't resolve this, so I just nuked the system and reinstalled. I am now using disk images to act as "Restore Points" like windows has.

Good news: after 2 reinstalls, it works! and I have also think I have found the _cause_ of all of this nonsense:

The OpenKinect libfreenect2 library

The page that is pointed to (either on your website tutorial or github README.md) shows how to gain access to packages that aren't on the default source list for some Ubuntu versions (notably 14.04.3, which is what I am using) using a few ppas, including 

ppa:deb-rob/ros-trusty

ppa:floe/libusb

From what I was able to gather, the deb-rob ppa is the main offender, and the floe/libusb one is fine, and I have submitted tickets to libfreenect2 and IAI_Kinect2 as well, which points to it. This issue appears to be that many of the libraries that both ros and your code depend on are needlessly upgraded by running `sudo apt-get update` after adding this repository, and then `apt` basically breaks your code and then breaks itself, unable to downgrade the new libraries.  In the mean time, though, I would suggest either explicitly documenting your own guide of how to install the Kinect v2 drivers, or at least not pointing to that.

Also, are there project files you could check in so this can be opened in QTCreator? or are none necessary?
Do you have any advice as to how to install the libfreenect2 library without this happening? Thanks.

Jon

**Comment by karlpauwels** [comment]
Great to hear it's working now!

I'm only pointing to IAI Kinect2 which is required. But yeah, both are in a very early stage so things change quickly. All I can tell you is that I'm only using ppa:floe/libusb and that works pretty smoothly. In general I'm very careful with adding external repositories.

Concerning QTCreator, have a look here: http://wiki.ros.org/IDEs#QtCreator
You can directly open the CMakeLists file (from the source folder). Just take care you're pointing to the correct build folder.

Karl
